#!/usr/bin/env python3
"""
Compare Screen - Report Footer HTML

Generates HTML footer section for comparison reports.

Author: AIMF LLC
Date: June 6, 2025
"""

import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def generate_report_footer_html(self):
    """Generate HTML footer section for comparison report
    
    Returns:
        str: HTML footer section
    """
    try:
        # Get current timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Generate footer HTML
        html = f"""
        <footer class="footer">
            <p>Generated by Pawprinting PyQt6 V2 on {timestamp}</p>
            <p>AIMF LLC &copy; 2025 | All Rights Reserved</p>
        </footer>
    </div>
</body>
</html>
        """
        
        logger.debug("Report footer HTML generated")
        return html
    except Exception as e:
        logger.error(f"Error generating report footer HTML: {str(e)}")
        return "</body></html>"
