#!/usr/bin/env python3
"""
Compare Screen - Report Footer

Creates HTML footer section for comparison reports.

Author: AIMF LLC
Date: June 6, 2025
"""

import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def create_report_footer(self, timestamp):
    """Create HTML footer for comparison report
    
    Args:
        timestamp: Report generation timestamp
        
    Returns:
        str: HTML footer content
    """
    # Format current date for footer
    current_date = datetime.now().strftime("%Y-%m-%d")
    
    # Create footer with dark theme styling and attribution
    html = f"""
        <footer style="margin-top: 40px; border-top: 1px solid #444444; padding-top: 20px; text-align: center; color: #999999;">
            <p>Generated by Pawprinting PyQt6 V2 | AIMF LLC | {current_date}</p>
            <p style="font-size: 0.8em;">Report ID: {timestamp}</p>
        </footer>
    </div>
    </body>
    </html>
    """
    return html
