#!/usr/bin/env python3
"""
Compare Screen - Report Conclusion

Creates HTML conclusion section for the comparison report.

Author: AIMF LLC
Date: June 6, 2025
"""

import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def create_report_conclusion(before_file, after_file):
    """Create HTML conclusion section for report
    
    Args:
        before_file: Path to the before comparison file
        after_file: Path to the after comparison file
        
    Returns:
        str: HTML content for conclusion section
    """
    try:
        # Get current timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Create HTML conclusion with dark theme styling
        conclusion_html = f"""
        <div class="section conclusion-section">
            <h2 class="section-header">Conclusion</h2>
            <p class="conclusion-text">
                This report compares pawprint patterns between the following files:
                <br><strong>Before:</strong> {before_file}
                <br><strong>After:</strong> {after_file}
            </p>
            <p class="report-timestamp">Report generated on {timestamp}</p>
            <p class="report-footer">Generated by Pawprinting Tool - AIMF LLC</p>
        </div>
        """
        
        logger.debug("Report conclusion HTML created")
        return conclusion_html
    except Exception as e:
        logger.error(f"Error creating report conclusion: {str(e)}")
        return f"<div class='section conclusion-section'><h2>Conclusion</h2><p>Report generated on {datetime.now().strftime('%Y-%m-%d')}</p></div>"
