name: Lint and Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort pylint mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Check with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Check with black
        run: |
          black --check --diff .
          
      - name: Check with isort
        run: |
          isort --check --diff .
          
      - name: Generate lint report
        if: success() || failure()
        run: |
          mkdir -p reports
          flake8 . --format=html --htmldir=reports/flake8 --exit-zero
          
      - name: Upload lint reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: reports/
